### ISSUE TITLE
Multiple actions & settings

### ISSUE THREAD

**Issue by cliffrowley** [mdonoughe/streamdeck-rs#1]
I've been looking through your source code & docs for a plugin I'd like to build - and I apologise in advance if I am missing something obvious as I'm just getting to grips with Rust - but it seems to me that currently streamdeck-rs doesn't support multiple actions within a plugin.

More specifically, am I right in thinking that by specifying the settings and property inspector serializers/deserializers with `StreamDeckSocket` (e.g. `<S>`, `<MI>`, `<MO>`) that all the actions would then need to share these same structures?

If not, sorry for the noise! I'm learning ;-)

**Comment by mdonoughe** [comment]
I haven't actually used them in a plugin yet, but the intention is to either use the same structs for all actions or to use enums, otherwise Serde wouldn't be able to deserialize that part of the json until the target action has been decided.

**Comment by cliffrowley** [comment]
Hm, interesting - I actually hadn't considered that you could use an enum here (as I say, new to Rust) but that does make sense.  I suspect most plugins will need different structures simply because settings are fairly specific to a context within each individual action (in order to restore a context's state on willAppear). I'll have a play and see what happens.

Thanks for responding, if nothing else you've aided my learning :-)
