### ISSUE TITLE
Socket missing iterator trait

### ISSUE THREAD

**Issue by PaigeM89** [mdonoughe/streamdeck-rs#2]
The example code for connecting to a socket uses `socket.for_each`. Unless I'm importing the wrong futures / async library (which is entirely possible - there's a lot in flux there!), the `StreamDeckSocket` struct is missing the `Iterator` implementation required for that function to work.

Here's my code:

```
extern crate tokio; //tokio 0.1.22

use streamdeck_rs::socket::*;
use streamdeck_rs::registration::*;
use crate::tokio::prelude::Future;
use std::env;

//struct fields don't matter for this example
struct GlobalSettings {
}
struct ActionSettings {
}
struct MessageToSd {
}
struct MessageFromSd {
}

fn register() {
    let params = RegistrationParams::from_args(env::args()).unwrap();
    let connect = StreamDeckSocket::<GlobalSettings, ActionSettings, MessageFromSd, MessageToSd>::connect(params.port, params.event, params.uuid);
    tokio::run(
        connect.map_err(|e| println!("connection failed: {:?}", e))
        .and_then(|socket| socket.for_each(|message| println!("recieved: {:?}", message))
            .map_err(|e| println!("read error: {:?}", e)))
    );
}
```

And here's my build error:
```
error[E0599]: no method named `for_each` found for type `streamdeck_rs::socket::StreamDeckSocket<GlobalSettings, ActionSettings, MessageFromSd, MessageToSd>` in the current scope
  --> src/main.rs:39:35
   |
39 |         .and_then(|socket| socket.for_each(|message| println!("recieved: {:?}", message))
   |                                   ^^^^^^^^
   |
   = note: the method `for_each` exists but the following trait bounds were not satisfied:
           `&mut streamdeck_rs::socket::StreamDeckSocket<GlobalSettings, ActionSettings, MessageFromSd, MessageToSd> : std::iter::Iterator`
```

Additionally, the trait can't be implemented outside the crate:
```
impl Iterator for StreamDeckSocket<GlobalSettings, ActionSettings, MessageFromSd, MessageToSd> {
    fn next(&mut self) -> Option<MessageFromSd> {
    }
}
```

yields

```
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
```

Which means the SDSocket would have to be wrapped locally? That doesn't seem like an ideal use case.

I'm very new to Rust so sorry in advance if I'm just doing everything wrong.

**Comment by mdonoughe** [comment]
That `for_each` is supposed to be [Stream::for_each](https://docs.rs/futures/0.1.28/futures/stream/trait.Stream.html#method.for_each).

**Comment by PaigeM89** [comment]
Importing futures::Stream gives 3 trait not implemented errors:


the method `for_each` exists but the following trait bounds were not satisfied:
           `&mut streamdeck_rs::socket::StreamDeckSocket<GlobalSettings, ActionSettings, MessageFromSd, MessageToSd> : futures::stream::Stream`
           `&mut streamdeck_rs::socket::StreamDeckSocket<GlobalSettings, ActionSettings, MessageFromSd, MessageToSd> : std::iter::Iterator`
           `streamdeck_rs::socket::StreamDeckSocket<GlobalSettings, ActionSettings, MessageFromSd, MessageToSd> : futures::stream::Stream


Based on your response, I'm thinking this is me not understanding rust imports very well, so I'll keep digging and try to update this when I figure it out.

**Comment by mdonoughe** [comment]
StreamDeckSocket implements Stream, but only if your message types are deserializable: https://github.com/mdonoughe/streamdeck-rs/blob/master/src/socket.rs#L80

**Comment by PaigeM89** [comment]
Yup, I was doing many things wrong. When I feel like I have a more solid grasp on things, I may make a PR with a minimal example for documentation. I'll close this issue.
